services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: infoverify
      MYSQL_USER: infoverify
      MYSQL_PASSWORD: infoverify_dev_only
      MYSQL_ROOT_PASSWORD: root_dev_only
    ports:
      - "3306:3306"
    volumes:
      - infoverify_mysql:/var/lib/mysql

volumes:
  infoverify_mysql:
