import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ApiError, api } from '../lib/api';
import { useAuth } from '../lib/auth';

export default function PinSetupPage() {
  const { refreshUser } = useAuth(); const nav = useNavigate(); const [step, setStep] = useState<'login' | 'transaction'>('login'); const [pin, setPin] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); if (pin.length !== (step === 'login' ? 6 : 4) || pin !== confirm) { setError('PINs must match and have the required number of digits.'); return; } setBusy(true); try { await api.post(step === 'login' ? '/user/login-pin/set' : '/user/pin/set', { pin }); if (step === 'login') { setStep('transaction'); setPin(''); setConfirm(''); } else { await refreshUser(); nav('/dashboard'); } } catch (e) { setError(e instanceof ApiError ? e.message : 'Could not save PIN.'); } finally { setBusy(false); } }
  const digits = step === 'login' ? 6 : 4;
  return <div className="flex min-h-screen items-center justify-center bg-cream px-5"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl border border-parchment-line bg-parchment p-7"><h1 className="font-display text-xl font-bold text-ink">Set up your {step === 'login' ? 'login' : 'transaction'} PIN</h1><p className="mt-2 text-sm text-ink-600">{step === 'login' ? 'Use this 6-digit PIN whenever you sign in on a new device.' : 'Use this 4-digit PIN to confirm wallet purchases.'}</p><label className="mt-6 block text-xs font-semibold text-ink-600">{digits}-digit PIN<input autoFocus required value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, '').slice(0, digits))} inputMode="numeric" type="password" className="mt-1 w-full rounded-lg border border-parchment-line bg-cream px-3 py-3 text-lg tracking-[0.5em] text-ink outline-none focus:border-gold-500" /></label><label className="mt-4 block text-xs font-semibold text-ink-600">Confirm PIN<input required value={confirm} onChange={(e) => setConfirm(e.target.value.replace(/\D/g, '').slice(0, digits))} inputMode="numeric" type="password" className="mt-1 w-full rounded-lg border border-parchment-line bg-cream px-3 py-3 text-lg tracking-[0.5em] text-ink outline-none focus:border-gold-500" /></label>{error && <p className="mt-3 text-sm text-ember-600">{error}</p>}<button disabled={busy || pin.length !== digits || confirm.length !== digits} className="mt-6 w-full rounded-lg bg-gold-500 py-3 font-bold text-ink disabled:opacity-50">{busy ? 'Saving…' : step === 'login' ? 'Continue' : 'Finish setup'}</button></form></div>;
}
