import { useEffect, useState, type FormEvent } from 'react';
import { Copy, Download } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { api } from '../lib/api';
import { PinConfirmDialog } from '../components/PinConfirmDialog';

export default function ResultPinPage({ exam }: { exam: 'WAEC' | 'NECO' | 'NABTEB' }) {
  const nav = useNavigate(); const [quantity, setQuantity] = useState(1); const [price, setPrice] = useState<number>(); const [showPin, setShowPin] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [pins, setPins] = useState<string[]>([]); const [reference, setReference] = useState('');
  useEffect(() => { api.get<{data:{unitPrice:number}}>(`/result/${exam.toLowerCase()}/price`).then(r => setPrice(Number(r.data.unitPrice))).catch(() => setMessage('Unable to load current price.')); }, [exam]);
  function prepare(e: FormEvent) { e.preventDefault(); if (price !== undefined) setShowPin(true); }
  async function purchase(pin: string) { setShowPin(false); setBusy(true); try { const r = await api.post<{status:boolean;message:string;data:{reference?:string;pin?:string;pins?:string[]}}>(`/result/${exam.toLowerCase()}/pin`, {quantity, pin}); if (!r.status) throw new Error(r.message); setMessage(r.message); setReference(r.data.reference ?? ''); setPins(r.data.pins?.length ? r.data.pins : r.data.pin ? [r.data.pin] : []); } catch (e) { setMessage(e instanceof Error ? e.message : 'Request failed.'); } finally { setBusy(false); } }
  function downloadPins() { const content = `MARIA Digital Solutions\n${exam} Result Checker PIN${pins.length > 1 ? 's' : ''}\nReference: ${reference || 'N/A'}\n\n${pins.join('\n')}`; const url = URL.createObjectURL(new Blob([content], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `${exam}-result-pins-${reference || 'download'}.txt`; link.click(); URL.revokeObjectURL(url); }
  const total = (price ?? 0) * quantity;
  return <AppShell><button onClick={() => nav('/result-checkers')}>← Result Checkers</button><main className="mx-auto mt-5 max-w-lg rounded-2xl border border-parchment-line bg-parchment p-6"><h1 className="font-display text-2xl font-bold text-ink">Buy {exam} PIN</h1><div className="mt-4 rounded-xl bg-cream p-4"><span className="font-body text-xs text-ink-600">Price per PIN</span><p className="font-mono text-xl font-bold text-gold-700">{price === undefined ? 'Loading…' : `₦${price.toLocaleString()}`}</p></div><form onSubmit={prepare} className="mt-4 space-y-4"><label>Quantity (1–10)<input type="number" min="1" max="10" value={quantity} onChange={e => setQuantity(Math.max(1, Math.min(10, Number(e.target.value) || 1)))} className="mt-1 w-full rounded-xl border p-3" /></label><button disabled={busy || price === undefined} className="w-full rounded-xl bg-gold-500 py-3 font-semibold">{busy ? 'Processing…' : `Continue — ₦${total.toLocaleString()}`}</button></form>{message && <div className="mt-4 rounded-xl bg-success-500/10 p-4">{message}{pins.map((pin, i) => <code key={i} className="mt-3 block rounded bg-cream p-3 font-bold">{pin}</code>)}{pins.length > 0 && <div className="mt-4 flex gap-3"><button onClick={() => navigator.clipboard.writeText(pins.join('\n'))} className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-parchment-line py-2 font-semibold"><Copy size={16} /> Copy</button><button onClick={downloadPins} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-gold-500 py-2 font-semibold"><Download size={16} /> Download</button></div>}</div>}</main><PinConfirmDialog open={showPin} onClose={() => setShowPin(false)} onVerified={purchase} /></AppShell>;
}

